version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - /netology/mysql/data:/var/lib/mysql
      - /netology/mysql/dump:/dump
    environment:
      MYSQL_ROOT_PASSWORD: netology
